### ISSUE TITLE
rss2 change rm_list 报错

### ISSUE THREAD

**Issue by Uejvvn** [mengshouer/HoshinoBot-Plugins#13]
[2023-01-16 18:53:23,607 nonebot] ERROR: An exception occurred while running command ('change',):
[2023-01-16 18:53:23,608 nonebot] ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nonebot/command/__init__.py", line 869, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/site-packages/nonebot/command/__init__.py", line 174, in run
    await self.func(session)
  File "/root/HoshinoBot/hoshino/modules/rss2/command/change_dy.py", line 214, in change
    changed_rss_list = await batch_change_rss(
  File "/root/HoshinoBot/hoshino/modules/rss2/command/change_dy.py", line 241, in batch_change_rss
    key_to_change, value_to_change = change_dict.split("=", 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by mengshouer** [comment]
输入了什么

**Comment by Uejvvn** [comment]
[2023-01-16 18:53:23,605 nonebot] INFO: Self: ****, Message -908929517 from ****: "change channel rm_list='test'"
