### ISSUE TITLE
error

### ISSUE THREAD

**Issue by IsaacTheMouse** [mengshouer/HoshinoBot-Plugins#8]
> Task exception was never retrieved
future: <Task finished name='Task-13' coro=<CQHttp._handle_event_with_response() done, defined at /home/ubuntu/.local/lib/python3.8/site-packages/aiocqhttp/__init__.py:606> exception=TypeError('list indices must be integers or slices, not str')>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 608, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 601, in _handle_event
    filter(lambda r: r is not None, await
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiocqhttp/bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiocqhttp/utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "/home/ubuntu/Hoshino/hoshino/modules/rss2/__init__.py", line 18, in start
    rss_list = Rss.read_rss()  # 读取list
  File "/home/ubuntu/Hoshino/hoshino/modules/rss2/rss_class.py", line 65, in read_rss
    return [Rss(rss) for rss in db.all()]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tinydb/table.py", line 233, in all
    return list(iter(self))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tinydb/table.py", line 636, in __iter__
    for doc_id, doc in self._read_table().items():
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tinydb/table.py", line 693, in _read_table
    table = tables[self.name]
TypeError: list indices must be integers or slices, not str

**Comment by mengshouer** [comment]
详细说明？我新拉一个hoshinobot，装完本体依赖和我这个依赖之后直接跑没发现啥问题

aiocache==0.11.1
aiocqhttp==1.4.2
aiodns==3.0.0
aiofiles==0.8.0
aiohttp==3.6.3
anyio==3.6.1
appdirs==1.4.4
APScheduler==3.9.1
arrow==1.2.2
async-timeout==3.0.1
attrs==21.2.0
backports.zoneinfo==0.2.1
bbcode==1.1.0
beautifulsoup4==4.9.3
black==22.3.0
blinker==1.4
cattrs==1.10.0
cchardet==2.1.7
certifi==2021.10.8
cffi==1.15.0
chardet==3.0.4
click==8.1.3
cloudscraper==1.2.60
colorama==0.4.4
cryptography==35.0.0
cssselect==1.1.0
cycler==0.11.0
Cython==0.29.24
deep-translator==1.8.3
emoji==1.7.0
feedparser==6.0.10
fuzzywuzzy==0.18.0
h11==0.12.0
h2==4.1.0
hpack==4.0.0
httpcore==0.15.0
httpx==0.23.0
hypercorn==0.13.2
hyperframe==6.0.1
idna==2.10
ImageHash==4.2.1
itsdangerous==2.1.2
Jinja2==3.0.3
jmespath==1.0.0
kiwisolver==1.4.2
langid==1.1.6
lxml==4.8.0
magneturi==1.3
MarkupSafe==2.1.1
matplotlib==3.2.2
multidict==4.7.6
mypy-extensions==0.4.3
nonebot==1.9.1
numpy==1.22.4
pathspec==0.9.0
peony-twitter==2.1.2
Pillow==9.1.1
platformdirs==2.5.2
priority==2.0.0
psutil==5.9.1
pycares==4.1.2
pycparser==2.21
pydantic==1.9.1
pygtrie==2.3.3
pyparsing==3.0.9
pyquery==1.4.3
python-dateutil==2.8.2
python-dotenv==0.20.0
python-magic==0.4.26
python-magic-bin==0.4.14
python-qbittorrent==0.4.2
pytz==2019.3
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.3.0
Quart==0.14.1
requests==2.23.0
requests-cache==0.9.4
requests-toolbelt==0.9.1
rfc3986==1.5.0
scipy==1.8.1
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.2.0
sogou-tr-free==0.0.11
soupsieve==2.3.2.post1
tenacity==8.0.1
tinydb==4.1.1
toml==0.10.2
tomli==2.0.1
typing_extensions==4.2.0
tzdata==2022.1
tzlocal==4.2
url-normalize==1.4.3
urllib3==1.25.11
Werkzeug==2.0.3
wincertstore==0.2
wsproto==0.15.0
yarl==1.5.1
zhconv==1.4.3

**Comment by IsaacTheMouse** [comment]
抱歉比较小白，不太清楚怎么描述。
装的东西多，环境比较乱：
https://paste.ubuntu.com/p/z4Zv5MfCQ2/
rss2装上之后lssv里看不到，但是showall能触发，控制台有记录。

> [2022-05-24 11:24:08,760 nonebot] ERROR: An exception occurred while running command ('showall',):
[2022-05-24 11:24:08,760 nonebot] ERROR: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/command/__init__.py", line 869, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/command/__init__.py", line 174, in run
    await self.func(session)
  File "/home/ubuntu/Hoshino/hoshino/modules/rss2/command/show_all.py", line 29, in rssShowAll
    rss_list = Rss.get_by_group(group_id=group_id)
  File "/home/ubuntu/Hoshino/hoshino/modules/rss2/rss_class.py", line 180, in get_by_group
    rss_old = Rss.read_rss()
  File "/home/ubuntu/Hoshino/hoshino/modules/rss2/rss_class.py", line 65, in read_rss
    return [Rss(rss) for rss in db.all()]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tinydb/table.py", line 233, in all
    return list(iter(self))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tinydb/table.py", line 636, in __iter__
    for doc_id, doc in self._read_table().items():
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tinydb/table.py", line 693, in _read_table
    table = tables[self.name]
TypeError: list indices must be integers or slices, not str

**Comment by mengshouer** [comment]
因为rss2不依赖于hoshino，原生nonebot1就能运行，所以lssv看不到

**Comment by IsaacTheMouse** [comment]
原来如此，但是rss2的showall add deldy等命令都没法正常执行，报错均与上面的相似。
请问我还应该提供什么信息呢？

**Comment by mengshouer** [comment]
运行目录下有没有data文件夹？ 删除缓存重新试试看？有个rss.json的文件

**Comment by IsaacTheMouse** [comment]
感谢指导，删除 Hoshino/data/rss.json 后命令能正常运行了。
但是好像还有别的问题。。。我确定有问题后再说吧。

**Comment by IsaacTheMouse** [comment]
确定了，之前剩下的应该是我自己代理配置的问题，一开始提到的问题已经解决了。再次感谢大佬答疑。
